# Generated by Django 5.0.2 on 2024-03-03 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_register_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.event'),
        ),
    ]
